function autocorregir() { 
  let texto = document.getElementById("texto").value;

  const correcciones = {
    // Tecnología y educación
    "\\bAI\\b": "Inteligencia Artificial",
    "\\bVR\\b": "Realidad Virtual",
    "\\bAR\\b": "Realidad Aumentada",
    "\\bSTEAM\\b": "Ciencia, Tecnología, Ingeniería, Arte y Matemáticas",
    "\\bSTEM\\b": "Ciencia, Tecnología, Ingeniería y Matemáticas",
    "\\bIoT\\b": "Internet de las Cosas",
    "\\bML\\b": "Aprendizaje Automático",
    "\\bDL\\b": "Aprendizaje Profundo",
    "\\bIT\\b": "Tecnologías de la Información",
    "\\bICT\\b": "Tecnologías de la Información y la Comunicación",
    "\\bCPU\\b": "Unidad Central de Procesamiento",
    "\\bGPU\\b": "Unidad de Procesamiento Gráfico",
    "\\bAPI\\b": "Interfaz de Programación de Aplicaciones",
    "\\bUI\\b": "Interfaz de Usuario",
    "\\bUX\\b": "Experiencia del Usuario",
    "\\bHTML\\b": "Lenguaje de Marcado de Hipertexto",
    "\\bCSS\\b": "Hojas de Estilo en Cascada",
    "\\bJS\\b": "JavaScript",
    "\\bSQL\\b": "Lenguaje de Consulta Estructurada",
    "\\bURL\\b": "Dirección Web",
    "\\bHTTP\\b": "Protocolo de Transferencia de Hipertexto",

    // Redes sociales y slang
    "\\bXD\\b": "risa o carcajada",
    "\\bLOL\\b": "riendo a carcajadas",
    "\\bOMG\\b": "¡Dios mío!",
    "\\bWTF\\b": "¿Qué demonios?",
    "\\bBRB\\b": "vuelvo enseguida",
    "\\bBTW\\b": "por cierto",
    "\\bTT\\b": "tendencia en redes sociales",
    "\\bDM\\b": "mensaje directo",
    "\\bIG\\b": "Instagram",
    "\\bFB\\b": "Facebook",
    "\\bYT\\b": "YouTube",
    "\\bTikTok\\b": "plataforma de videos cortos",
    "\\bFYP\\b": "Para ti (página principal en TikTok)",
    "\\bNSFW\\b": "contenido no apto para el trabajo",
    "\\bTBT\\b": "jueves de recuerdo",
    "\\bCRINGE\\b": "vergonzoso o incómodo",
    "\\bBAE\\b": "persona querida (novio/a)",
    "\\bBFF\\b": "mejor amigo/a para siempre",
    "\\bAF\\b": "muy",
    "\\bFTW\\b": "para ganar / lo mejor",
    "\\bGG\\b": "buen juego",
    "\\bNOOB\\b": "novato sin experiencia",
    "\\bPOV\\b": "punto de vista",
    "\\bIDK\\b": "no lo sé",
    "\\bILY\\b": "te quiero",
    "\\bGRWM\\b": "prepárate conmigo",
    "\\bASMR\\b": "sonidos que generan placer sensorial",
    "\\bTLDR\\b": "resumen rápido",
    "\\bIRL\\b": "en la vida real",
    "\\bJK\\b": "es broma",
    "\\bRN\\b": "ahora mismo",

    // Abreviaciones informales (minúscula con \b)
    "\\btqm\\b": "te quiero mucho",
    "\\btkm\\b": "te kiero mucho",
    "\\bxfa\\b": "por favor",
    "\\bxq\\b": "porque",
    "\\bxk\\b": "porque",
    "\\bx\\b": "por",
    "\\bq\\b": "que",
    "\\bk\\b": "que",
    "\\bbn\\b": "bien",
    "\\bmal\\b": "mal",
    "\\btoy\\b": "estoy",
    "\\bntp\\b": "no te preocupes",
    "\\bnp\\b": "no pasa nada",
    "\\btbn\\b": "también",
    "\\btmb\\b": "también",
    "\\bnls\\b": "no lo sé",
    "\\bsalu2\\b": "saludos",
    "\\bgrax\\b": "gracias",
    "\\bholi\\b": "hola",
    "\\bbye\\b": "adiós",
    "\\ba2\\b": "adiós",
    "\\bbb\\b": "bebé",
    "\\bbby\\b": "bebé",
    "\\bxoxo\\b": "besos y abrazos",
    "\\buwu\\b": "emoticon tierno",
    "\\bowo\\b": "emoticon sorprendido",
    "\\bqtl\\b": "qué tal",
    "\\bidc\\b": "no me importa",

    // Tecnología y gaming
    "\\bafk\\b": "lejos del teclado",
    "\\bgg\\b": "buen juego",
    "\\bnoob\\b": "novato sin experiencia",
    "\\bop\\b": "muy poderoso",
    "\\bbrb\\b": "vuelvo enseguida",
    "\\bfps\\b": "cuadros por segundo",
    "\\brpg\\b": "juego de rol",
    "\\bnpc\\b": "personaje no jugable",
    "\\blan\\b": "red de área local",
    "\\busb\\b": "puerto universal serial",
    "\\bwifi\\b": "red inalámbrica",
    "\\bping\\b": "latencia",

    // Slang internacional
    "\\bikr\\b": "¡lo sé, verdad!",
    "\\bttyl\\b": "hablamos luego",
    "\\bomg\\b": "¡dios mío!",
    "\\bwtf\\b": "¿qué demonios?",
    "\\blol\\b": "me estoy riendo",
    "\\brofl\\b": "riendo en el suelo",
    "\\bsmh\\b": "negando con la cabeza",
    "\\btbh\\b": "para ser honesto",
    "\\bfomo\\b": "miedo a perderse algo",
    "\\bgoat\\b": "el mejor de todos los tiempos",
    "\\bcap\\b": "mentira",
    "\\bnocap\\b": "verdad",
    "\\bratio\\b": "más respuestas que likes",
    "\\bw\\b": "victoria",
    "\\bl\\b": "derrota",
    "\\bslay\\b": "lucirse"
  };

  for (const abreviacion in correcciones) {
    const regex = new RegExp(abreviacion, "gi");
    texto = texto.replace(regex, correcciones[abreviacion]);
  }

  document.getElementById("resultado").textContent = texto;
}
