function autocorregir() { 
  let texto = document.getElementById("texto").value;

  const correcciones = {
    // Tecnología y educación
    "\\bAI\\b": "Inteligencia Artificial",
    "\\bVR\\b": "Realidad Virtual",
    "\\bAR\\b": "Realidad Aumentada",
    "\\bSTEAM\\b": "Ciencia, Tecnología, Ingeniería, Arte y Matemáticas",
    "\\bSTEM\\b": "Ciencia, Tecnología, Ingeniería y Matemáticas",
    "\\bIoT\\b": "Internet de las Cosas",
    "\\bML\\b": "Aprendizaje Automático",
    "\\bDL\\b": "Aprendizaje Profundo",
    "\\bIT\\b": "Tecnologías de la Información",
    "\\bICT\\b": "Tecnologías de la Información y la Comunicación",
    "\\bCPU\\b": "Unidad Central de Procesamiento",
    "\\bGPU\\b": "Unidad de Procesamiento Gráfico",
    "\\bAPI\\b": "Interfaz de Programación de Aplicaciones",
    "\\bUI\\b": "Interfaz de Usuario",
    "\\bUX\\b": "Experiencia del Usuario",
    "\\bHTML\\b": "Lenguaje de Marcado de Hipertexto",
    "\\bCSS\\b": "Hojas de Estilo en Cascada",
    "\\bJS\\b": "JavaScript",
    "\\bSQL\\b": "Lenguaje de Consulta Estructurada",
    "\\bURL\\b": "Dirección Web",
    "\\bHTTP\\b": "Protocolo de Transferencia de Hipertexto",

    // Redes sociales y slang
    "\\bXD\\b": "risa o carcajada",
    "\\bLOL\\b": "riendo a carcajadas",
    "\\bOMG\\b": "¡Dios mío!",
    "\\bWTF\\b": "¿Qué demonios?",
    "\\bBRB\\b": "vuelvo enseguida",
    "\\bBTW\\b": "por cierto",
    "\\bTT\\b": "tendencia en redes sociales",
    "\\bDM\\b": "mensaje directo",
    "\\bIG\\b": "Instagram",
    "\\bFB\\b": "Facebook",
    "\\bYT\\b": "YouTube",
    "\\bTikTok\\b": "plataforma de videos cortos",
    "\\bFYP\\b": "Para ti (página principal en TikTok)",
    "\\bNSFW\\b": "contenido no apto para el trabajo",
    "\\bTBT\\b": "jueves de recuerdo",
    "\\bCRINGE\\b": "vergonzoso o incómodo",
    "\\bBAE\\b": "persona querida (novio/a)",
    "\\bBFF\\b": "mejor amigo/a para siempre",
    "\\bAF\\b": "muy",
    "\\bFTW\\b": "para ganar / lo mejor",
    "\\bGG\\b": "buen juego",
    "\\bNOOB\\b": "novato sin experiencia",
    "\\bPOV\\b": "punto de vista",
    "\\bIDK\\b": "no lo sé",
    "\\bILY\\b": "te quiero",
    "\\bGRWM\\b": "prepárate conmigo",
    "\\bASMR\\b": "sonidos que generan placer sensorial",
    "\\bTLDR\\b": "resumen rápido",
    "\\bIRL\\b": "en la vida real",
    "\\bJK\\b": "es broma",
    "\\bRN\\b": "ahora mismo",

    // Abreviaciones informales (en minúscula)
    "tqm": "te quiero mucho",
    "tkm": "te kiero mucho",
    "xfa": "por favor",
    "xq": "porque",
    "xk": "porque",
    "\\bx\\b": "por",
    "\\bq\\b": "que",
    "\\bk\\b": "que",
    "bn": "bien",
    "mal": "mal",
    "toy": "estoy",
    "ntp": "no te preocupes",
    "np": "no pasa nada",
    "tbn": "también",
    "tmb": "también",
    "nls": "no lo sé",
    "salu2": "saludos",
    "grax": "gracias",
    "holi": "hola",
    "bye": "adiós",
    "a2": "adiós",
    "bb": "bebé",
    "bby": "bebé",
    "xoxo": "besos y abrazos",
    "uwu": "emoticon tierno",
    "owo": "emoticon sorprendido",
    "qtl": "qué tal",
    "idc": "no me importa",

    // Tecnología y gaming (minúsculas)
    "afk": "lejos del teclado",
    "gg": "buen juego",
    "noob": "novato sin experiencia",
    "op": "muy poderoso",
    "brb": "vuelvo enseguida",
    "fps": "cuadros por segundo",
    "rpg": "juego de rol",
    "npc": "personaje no jugable",
    "lan": "red de área local",
    "usb": "puerto universal serial",
    "wifi": "red inalámbrica",
    "ping": "latencia",

    // Slang internacional (minúscula)
    "ikr": "¡lo sé, verdad!",
    "ttyl": "hablamos luego",
    "omg": "¡dios mío!",
    "wtf": "¿qué demonios?",
    "lol": "me estoy riendo",
    "rofl": "riendo en el suelo",
    "smh": "negando con la cabeza",
    "tbh": "para ser honesto",
    "fomo": "miedo a perderse algo",
    "goat": "el mejor de todos los tiempos",
    "cap": "mentira",
    "nocap": "verdad",
    "ratio": "más respuestas que likes",
    "w": "victoria",
    "l": "derrota",
    "slay": "lucirse"
  };

  for (const abreviacion in correcciones) {
    const regex = new RegExp(abreviacion, "gi");
    texto = texto.replace(regex, correcciones[abreviacion]);
  }

  document.getElementById("resultado").textContent = texto;
}
